name: Go Deep Analysis
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Go Environment
        run: go env
      - name: Verify Go Modules
        run: go mod verify
      - name: Build
        run: go build -v ./...
        # does this one matter for a package?
      - name: Run tests with Race Detector
        run: go test -race -vet=off ./pkg/...
      - name: Run integration tests
        run: echo "integration test placeholder"