name: Go Deep Analysis
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Configure Go private modules
        run: |
          git config --global url."https://$GITHUB_ACCESS_TOKEN@github.com/".insteadOf "https://github.com/"
        env:
          GOPRIVATE: github.com/confidentsecurity/*
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACTIONS_PAT }}
      - name: Go Environment
        run: go env
      - name: Verify Go Modules
        run: go mod verify
      - name: Build
        run: go build -v ./...
        # does this one matter for a package?
      - name: Run tests with Race Detector
        run: go test -race -vet=off ./pkg/...
      - name: Run integration tests
        run: echo "integration test placeholder"